### ISSUE TITLE
Issue with suffix() value starting with space

### ISSUE THREAD

**Issue by dudesquare** [jcoc611/InputAffix#1]
When I use the suffix() method with a value that starts with a space (e.g. ' Suffix'), and I then type some text followed by a space, the cursor in the input is reset to the beginning and any text already inputted is deleted.

See the fiddle here: https://jsfiddle.net/sjoerdvosse/hfhp6njc/

**Comment by jcoc611** [comment]
General issue: when typing something that matches the suffix, but isn't the suffix (i.e the first few characters of that which is being typed is the same as the suffix, but then a character differs), the code deletes the current value and sets the cursor to the beginning.

Will fix by re-appending suffix instead, if the suffix has partially been matched.
